export const recoilAtomKeys = {
  USER: 'USER',
  IS_LOADING: 'IS_LOADING',
  IS_SHOW_SCREEN_SPINNER: 'IS_SHOW_SCREEN_SPINNER',
  MODAL: 'MODAL',
  IS_PREVIEW: 'IS_PREVIEW',
  GENERATED_CODE: 'GENERATED_CODE',
  PREVIEW_CODE: 'PREVIEW_CODE',
  DOCUMENTS_CODE: 'DOCUMENTS_CODE'
}

export const recoilSelectorKeys = {
  IS_PREVIEW_SELECTOR: 'IS_PREVIEW_SELECTOR'
}
